language: java
jdk:
  - oraclejdk8
cache:
  directories:
  - "$HOME/.m2"
install:
- curl -o $HOME/.m2/settings.xml https://raw.githubusercontent.com/andreasaronsson/maven-plugins/master/src/main/resources/settings.xml
- mvn dependency:go-offline
